### ISSUE TITLE
devweb works...docker container /new does not

### ISSUE THREAD

**Issue by tomsherrod** [coreos/discovery.etcd.io#30]
Running from devweb, works fine. 
build-docker...a /new results in "unable to generate token".  
docker logs: 06/Jun/2015:15:47:41 +0000] "GET /new HTTP/1.1" 400 25
setupToken returned: Couldn't setup state <nil> 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

Calling a url with a token returns valid results.

Any pointers on the /new error running in a container?

Thanks,
Tom

**Comment by madharjan** [comment]
The error "All the given peers are not reachable" is because discovery.etc.io is not able to connect to any etcd cluster. Default is to connect to 'http://127.0.0.1:4001' which is not available in a docker container.

See below for fix
https://github.com/madharjan/discovery.etcd.io/commit/2c38e005fb1209228f77e201c674c92622e9acd0

**Comment by isaiah** [comment]
Meh, if I already have a cluster, why would I want this thingie.

**Comment by tschuy** [comment]
Fixed in #43.
